import js from '@eslint/js';
import globals from 'globals';
import pluginVue from 'eslint-plugin-vue';
import { defineConfigWithVueTs, vueTsConfigs } from '@vue/eslint-config-typescript';

export default defineConfigWithVueTs(
  {
    // Generated by scripts/sync-shared.mjs, and dist/ is build output.
    ignores: ['dist', 'src/lib/shared', 'src/styles/tokens.css'],
  },
  {
    files: ['**/*.{ts,vue}'],
    languageOptions: { ecmaVersion: 2022, globals: globals.browser },
  },
  js.configs.recommended,
  ...pluginVue.configs['flat/recommended'],
  vueTsConfigs.recommended,
  {
    rules: {
      '@typescript-eslint/no-unused-vars': ['error', { argsIgnorePattern: '^_' }],
      // Chapter components are single-instance by design; "ChSectors" reads
      // better in the imports than "TheSectorsChapter".
      'vue/multi-word-component-names': 'off',
      // Template whitespace and attribute wrapping belong to Prettier; leaving
      // these on means every formatted file reports dozens of false warnings.
      'vue/max-attributes-per-line': 'off',
      'vue/singleline-html-element-content-newline': 'off',
      'vue/html-self-closing': 'off',
      'vue/html-indent': 'off',
      'vue/html-closing-bracket-newline': 'off',
      'vue/attributes-order': 'off',
    },
  },
);
